# NOTE: This workflow is for the template master repo only. You can remove it from your fork.

name: Docker build and push

on:
  schedule:
    - cron: "0 0 1 * *" # Update monthly
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    # Only run on the template's master repo
    if: ${{ github.repository == 'so298/singlecell-devcontainer' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # See https://github.com/docker/login-action#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .devcontainer/
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
